IS_694_TABLE_9 = {
    6: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 0.9, "max_overall_diameter_mm": 9.5},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 10.0},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 10.5},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 12.4},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 14.5},
    },
    7: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 0.9, "max_overall_diameter_mm": 9.5},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 10.0},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 10.5},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 12.4},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 14.5},
    },
    8: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 11.1},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 11.8},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 12.4},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 14.7},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 17.3},
    },
    9: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 11.8},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 12.4},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 13.1},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 15.6},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 18.3},
    },
    10: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 12.0},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 12.7},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 13.4},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 16.0},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 18.7},
    },
    11: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 12.0},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 12.7},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 13.4},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 16.0},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 18.7},
    },
    12: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 12.4},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 13.1},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 13.9},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 16.5},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 19.4},
    },
    13: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.0, "max_overall_diameter_mm": 13.1},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 13.8},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 14.6},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 17.4},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 20.5},
    },
    14: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 13.1},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 13.8},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 14.6},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 17.4},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 20.5},
    },
    15: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 13.5},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 14.3},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 15.1},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 18.1},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 21.3},
    },
    16: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 13.8},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 14.6},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 15.4},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 18.4},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 21.7},
    },
    17: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 14.6},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 15.4},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 16.3},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 19.5},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 23.0},
    },
    18: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 14.6},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 15.4},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 16.3},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 19.5},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 23.3},
    },
    19: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.1, "max_overall_diameter_mm": 14.6},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 15.4},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 16.3},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 19.5},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 23.8},
    },
    20: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 15.4},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 16.3},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 17.3},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 20.7},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.5, "max_overall_diameter_mm": 24.4},
    },
    21: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 15.4},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 16.3},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 17.3},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 20.7},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.5, "max_overall_diameter_mm": 25.0},
    },
    22: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 16.3},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 17.3},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 18.2},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 21.9},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.5, "max_overall_diameter_mm": 25.8},
    },
    23: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 16.3},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 17.3},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 18.2},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 21.9},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.5, "max_overall_diameter_mm": 26.3},
    },
    24: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 17.1},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 18.2},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 19.2},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 23.0},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.5, "max_overall_diameter_mm": 27.2},
    },
    25: {
        0.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.2, "max_overall_diameter_mm": 17.1},
        0.75: {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.3, "max_overall_diameter_mm": 19.0},
        1.0:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 19.2},
        1.5:  {"nominal_insulation_ti_mm": 0.6, "nominal_sheath_ts_mm": 1.4, "max_overall_diameter_mm": 23.0},
        2.5:  {"nominal_insulation_ti_mm": 0.7, "nominal_sheath_ts_mm": 1.5, "max_overall_diameter_mm": 27.0},
    }
}