from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import ForeignKey
from datetime import datetime
from online_version.extension.sqlmodel import db

#This databse model will be used for analytics where one can see the wire produced and total cost
class AnalyticsDB(db.Model):
    user = relationship("User", back_populates="analytics")
    user_id: Mapped[int] = mapped_column(ForeignKey("user.id"))
    id: Mapped[int] = mapped_column(primary_key=True)
    order_id: Mapped[str] = mapped_column(unique=True)
    timestamp: Mapped[datetime] = mapped_column(default=datetime.now)
    idempotency_key: Mapped[str] = mapped_column(unique = True)
    wire_type: Mapped[str] = mapped_column()
    table_ref: Mapped[str] = mapped_column()
    conductor_class: Mapped[str] = mapped_column()
    variant: Mapped[str] = mapped_column()
    material: Mapped[str] = mapped_column()
    conductor_weight_kg: Mapped[float] = mapped_column()
    aluminium_weight_kg: Mapped[float] = mapped_column()
    copper_rate_per_kg: Mapped[float] = mapped_column()
    metal_rate_per_kg: Mapped[float] = mapped_column()
    pvc_rate_per_kg: Mapped[float] = mapped_column()
    pvc_weight_kg: Mapped[float] = mapped_column()
    weight_per_meter_kg: Mapped[float] = mapped_column()
    cost_per_meter: Mapped[float] = mapped_column()
    total_cost: Mapped[float] = mapped_column()
    length_meters: Mapped[int] = mapped_column()
    
#This database saves the wire and its measurements.
class OrdersDB(db.Model):
    user = relationship("User", back_populates="orders")
    user_id: Mapped[int] = mapped_column(ForeignKey("user.id"))
    id: Mapped[int] = mapped_column(primary_key=True,)
    order_id: Mapped[str] = mapped_column(unique=True)
    timestamp: Mapped[datetime] = mapped_column(default=datetime.now)
    idempotency_key: Mapped[str] = mapped_column(unique = True)
    wire_type: Mapped[str] = mapped_column()
    variant: Mapped[str] = mapped_column()
    material: Mapped[str] = mapped_column()
    nominal_area_sqmm: Mapped[float] = mapped_column()
    number_of_cores: Mapped[int] = mapped_column()
    conductor_class: Mapped[str] = mapped_column()
    nominal_insulation_ti_mm: Mapped[float] = mapped_column()
    nominal_sheath_ts_mm: Mapped[float] = mapped_column()
    max_width_mm: Mapped[float] = mapped_column()
    max_height_mm: Mapped[float] = mapped_column()
    max_overall_diameter_mm: Mapped[float] = mapped_column()
    max_twisted_diameter_mm: Mapped[float] = mapped_column()
    recommended_core_layup: Mapped[float] = mapped_column()
    strand_diameter_mm: Mapped[float] = mapped_column()
    tolerance_percent: Mapped[float] = mapped_column()
    number_of_strands_per_core: Mapped[int] = mapped_column()
    number_of_strands: Mapped[int] = mapped_column()
    insulation_percent: Mapped[float] = mapped_column()
    inner_layer_percent: Mapped[float] = mapped_column()
    outer_layer_percent: Mapped[float] = mapped_column()
    bedding_percent: Mapped[float] = mapped_column()
    sheath_percent: Mapped[float] = mapped_column()
    length_meters: Mapped[int] = mapped_column()    

#This database saves the user and mail.   
class User(db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(unique=True)
    email: Mapped[str] = mapped_column(unique=True)
    password: Mapped[str] = mapped_column()
    orders = relationship("OrdersDB", back_populates="user")
    analytics = relationship("AnalyticsDB", back_populates="user")
    outbox = relationship("OutboxDB", back_populates="user")
    
class OutboxDB(db.Model):
    user = relationship("User", back_populates="outbox")
    user_id: Mapped[int] = mapped_column(ForeignKey("user.id"))
    id: Mapped[int] = mapped_column(primary_key=True,)
    order_id: Mapped[str] = mapped_column(unique=True)
    timestamp: Mapped[datetime] = mapped_column(default=datetime.now)
    idempotency_key: Mapped[str] = mapped_column(unique = True)
    wire_type: Mapped[str] = mapped_column()
    variant: Mapped[str] = mapped_column()
    material: Mapped[str] = mapped_column()
    nominal_area_sqmm: Mapped[float] = mapped_column()
    number_of_cores: Mapped[int] = mapped_column()
    conductor_class: Mapped[str] = mapped_column()
    nominal_insulation_ti_mm: Mapped[float] = mapped_column()
    nominal_sheath_ts_mm: Mapped[float] = mapped_column()
    max_width_mm: Mapped[float] = mapped_column()
    max_height_mm: Mapped[float] = mapped_column()
    max_overall_diameter_mm: Mapped[float] = mapped_column()
    max_twisted_diameter_mm: Mapped[float] = mapped_column()
    recommended_core_layup: Mapped[float] = mapped_column()
    strand_diameter_mm: Mapped[float] = mapped_column()
    tolerance_percent: Mapped[float] = mapped_column()
    number_of_strands_per_core: Mapped[int] = mapped_column()
    number_of_strands: Mapped[int] = mapped_column()
    insulation_percent: Mapped[float] = mapped_column()
    inner_layer_percent: Mapped[float] = mapped_column()
    outer_layer_percent: Mapped[float] = mapped_column()
    bedding_percent: Mapped[float] = mapped_column()
    sheath_percent: Mapped[float] = mapped_column()
    length_meters: Mapped[int] = mapped_column()
    status: Mapped[str] = mapped_column(default='pending')    